[package]
name = "confique"
version = "0.1.4"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

description = "Type-safe, layered, light-weight, `serde`-based configuration library"
documentation = "https://docs.rs/confique/"
repository = "https://github.com/LukasKalbertodt/confique/"
readme = "README.md"
license = "MIT/Apache-2.0"

keywords = ["config", "configuration", "conf", "serde", "type-safe"]
categories = ["config"]
exclude = [".github"]


[[example]]
name = "simple"
required-features = ["toml"]


[features]
default = ["toml", "yaml"]
yaml = ["serde_yaml"]


[dependencies]
confique-macro = { version = "=0.0.4", path = "macro" }
serde = { version = "1", features = ["derive"] }
serde_yaml = { version = "0.8", optional = true }
toml = { version = "0.5", optional = true }

[dev-dependencies]
pretty_assertions = "1.2.1"
